spring:
  profiles:
    include: oauth

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true

  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem://localhost/~/testdb;MODE=MYSQL

  mustache:
    suffix: .mustache
    prefix: classpath:/templates/